[package]
name = "rocket-sentry"
version = "0.1.0"
edition = "2018"

# Metadata
authors = ["Marti Raudsepp <marti@juffo.org>"]
description = "Simple add-on for the Rocket web framework to simplify integration with the Sentry application monitoring system."
homepage = "https://github.com/intgr/rocket-sentry"
repository = "https://github.com/intgr/rocket-sentry"
readme = "README.md"
keywords = ["rocket", "fairing", "sentry", "monitoring", "error-reporting"]
categories = ["web-programming", "development-tools"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sentry = "0.12.0"
rocket = { version = "0.4.2", default-features = false }

[workspace]
members = [
	"example"
]
